config/routes.rb
Portafolio::Application.routes.draw do

  get "welocme/index"
  get 'contact' => 'contact#new', as: 'contact'
  post 'contact' => 'contact#create', as: 'contact'

  match '/admin', to: 'admin/sessions#new'
  match '/admin/logout', to: 'admin/sessions#destroy', via: :delete

     namespace :admin do
        resources :sessions, only: [:new, :create]
        resources :projects
        resources :labels
        resources :users
        resources :skills
     end

   root :to => 'welcome#index'

end

app/models/skill.rb
# == Schema Information
#
# Table name: skills
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  percent    :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Skill < ActiveRecord::Base
  attr_accessible :name, :percent, :user
  belongs_to :user
  has_and_belongs_to_many :projects
end

app/controllers/admin/skills_controller.rb
class Admin::SkillsController < ApplicationController
  layout 'admin'
  before_filter :auth
  def index
    @skills = Skill.all
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(params[:skill])
    if @skill.save
      redirect_to [:admin, @skill], :notice => "Successfully created skill."
    else
      render :action => 'new'
    end
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update_attributes(params[:skill])
      redirect_to [:admin, @skill], :notice  => "Successfully updated skill."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    redirect_to admin_skills_url, :notice => "Successfully destroyed skill."
  end
end

app/helpers/admin/skills_helper.rb
module Admin::SkillsHelper
end

app/views/admin/skills/_form.html.erb
<%= form_for [:admin, @skill] do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :percent %><br />
    <%= f.number_field :percent %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/skills/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin, @skill] %> |
  <%= link_to "View All", admin_skills_path %>
</p>

app/views/admin/skills/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Percent</th>
  </tr>
  <% @skills.each do |skill| %>
    <tr>
      <td><%= skill.name %></td>
      <td><%= skill.percent %></td>
      <td><%= link_to "Show", [:admin, skill] %></td>
      <td><%= link_to "Edit", edit_admin_skill_path(skill) %></td>
      <td><%= link_to "Destroy", [:admin, skill], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Admin/Skill", new_admin_skill_path %></p>

app/views/admin/skills/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", admin_skills_path %></p>

app/views/admin/skills/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>
<p>
  <strong>Percent:</strong>
  <%= @skill.percent %>
</p>

<p>
  <%= link_to "Edit", edit_admin_skill_path(@skill) %> |
  <%= link_to "Destroy", [:admin, @skill], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_skills_path %>
</p>