config/routes.rb
Portafolio::Application.routes.draw do

  get "welocme/index"
  get 'contact' => 'contact#new', as: 'contact'
  post 'contact' => 'contact#create', as: 'contact'

  match '/admin', to: 'admin/sessions#new'
  match '/admin/logout', to: 'admin/sessions#destroy', via: :delete

     namespace :admin do
        resources :sessions, only: [:new, :create]
        resources :projects
        resources :labels
        resources :users
        resources :skills
     end

   root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @proyectos = Project.order("created_at DESC").all
    @users = User.find ( 1 )
    @arrayname = []
    @arrayper = []
    @users.skills.each do |s|
      @arrayname << s.name
      @arrayper << s.percent
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% content_for :header do %>
  <div class="row">
    <div class="large-3 columns">
      <h1><img src="/assets/gafas.png" /></h1>
    </div>
    <div class="large-9 columns">
      <hgroup>
        <h2><%= @users.name %></h2>
        <h4><%= @users.ocupacion %></h4>
        <p>Github: <a href="<%= @users.github %>" target="_blank"><%= @users.github %></a></p>
        <p>Linkedin: <a href="<%= @users.linkedin %>" target="_blank"><%= @users.linkedin %></a></p>
      </hgroup>
    </div>
   </div>
 <% end%>
  
<!-- End Header and Nav -->
 
<!-- First Band (Slider) -->
 
<div class="borbottom">
  <div class="row">
    <div class="large-6 columns">
      <h4>Descripción</h4>
      <p><%= @users.descriptin %></p>
    </div>
    <div class="large-6 columns">
      <div id="container">
      </div>
    </div>
  </div>
</div>
  
<!-- Three-up Content Blocks proyectos -->
 
<div class="marbottom">
  <div class="row">
  <h4>Proyectos realizados</h4>
  <% @proyectos.each do |p|%>
      <div class="large-3 columns contProy end">
        <figure>
          <a class="th radius"><%= image_tag p.photo.url, width: "100%" %></a>
        </figure>
        <h4><%= p.name %></h4>
        <%= link_to p.url, p.url, target: "_blank", class: 'btnUrl'  %>
        <span class="subheader year">related year: <%= p.year %></span>
        <p><%= p.desc_corta %></p>
        <div class="panel">
          <% p.skills.each do |s|%>
            <div class="label secondary"><%= s.name %></div>
          <% end%>
        </div>
      </div>
    <% end%>
  </div>
</div>
    
<!-- Call to Action Panel -->
<div class="row">
    <div class="large-12 columns">
    
      <div class="panel">
        <h4>Contacto</h4>
        <div class="row">
          <div class="large-6 columns">
            <%= form_tag contact_path do %>
              <%= fields_for :contact do |f| %>
                <p>
                  <%= f.label 'nombre'%>
                  <%= f.text_field :name %>
                </p>
                <p>
                  <%= f.label 'e-mail'%>
                  <%= f.text_field :mail %>
                </p>
                <p>
                  <%= f.label 'mensaje'%>
                  <%= f.text_area :message %>
                </p>
                <p>
                  <%= f.submit 'enviar', class: 'radius button small right' %>
                </p>
              <% end%>
            <% end %>
          </div>
          <div class="large-6 columns">
          </div>
        </div>
      </div>
      
    </div>
  </div>
 
  <!-- Footer -->
  
  <%= content_for :footer do %>
    <hr />
    <div class="large-12 columns">
      <div class="row">
        <div class="large-9 columns">
          <!-- AddThis Button BEGIN -->
          <div class="addthis_toolbox addthis_default_style ">
            <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
            <a class="addthis_button_tweet"></a>
            <a class="addthis_counter addthis_pill_style"></a>
          </div>
          <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
          <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=jose4125"></script>
          <!-- AddThis Button END -->
        </div>
        <div class="large-3 columns">
          <ul class="inline-list right contFollow">
            <li></li>
            <li>
              <span>Follow me</span>
                <a class="addthis_button_twitter_follow" addthis:userid="jd4125"></a>
                <a class="addthis_button_linkedin_follow" addthis:userid="josedavidlombana"></a>
                <a class="addthis_button_google_follow" addthis:userid="107616955910551901241"></a>
              <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-50967f6b452e735b"></script>
            </li>
          </ul>
        </div>
      </div>
    </div> 
  <% end %>
  <% content_for :footer_scripts do %>
    <%= javascript_tag do%>
      var cat = <%=raw @arrayname %> 
      var per = <%=raw @arrayper %> 
      $(document).on( 'ready', chart )
    <% end %>
  <% end %>