config/routes.rb
Portafolio::Application.routes.draw do

  get "welocme/index"
  get 'contact' => 'contact#new', as: 'contact'
  post 'contact' => 'contact#create', as: 'contact'

  match '/admin', to: 'admin/sessions#new'
  match '/admin/logout', to: 'admin/sessions#destroy', via: :delete

     namespace :admin do
        resources :sessions, only: [:new, :create]
        resources :projects
        resources :labels
        resources :users
        resources :skills
     end

   root :to => 'welcome#index'

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  description        :text
#  imagen             :string(255)
#  desc_corta         :string(255)
#  url                :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  photo_file_name    :string(255)
#  photo_content_type :string(255)
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#  year               :integer
#

class Project < ActiveRecord::Base
  attr_accessible :desc_corta, :description, :imagen, :name, :url, :skill_ids, :photo, :year
  has_and_belongs_to_many :skills
  has_attached_file :photo, style: { medium: '300X300>'},
                    :default_url => '/assets/default.jpg',
                    url: "/:attachment/:id/:style/:basename.:extension",
                    path: ":rails_root/public/:attachment/:id/:style/:basename.:extension"

  validates_attachment_size :photo, less_than: 5.megabytes
  validates_attachment_content_type :photo, content_type: ['image/jpeg', 'image/png']

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  layout 'admin'
  before_filter :auth
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to [:admin, @project], notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    params[:project][:skill_ids] ||= []
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to [:admin, @project], notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to admin_projects_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project], :html => { :multipart => true } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :imagen %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :desc_corta %><br />
    <%= f.text_field :desc_corta %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%=  f.select(:year, 2000..Time.now.year, :selected=>(f.object.year || Time.now.year)) %>
  </div>
  <div class="field">
    <% Skill.all.each do |s|%>
      <%= check_box_tag 'project[skill_ids][]', s.id, @project.skills.include?( s ) %>
      <%= label_tag s.name %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @project] %> |
<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Imagen</th>
    <th>Desc corta</th>
    <th>Url</th>
    <th>Year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.description %></td>
    <td><%= project.imagen %></td>
    <td><%= project.desc_corta %></td>
    <td><%= project.url %></td>
    <td><%= project.year %></td>
    <td><%= link_to 'Show', [:admin, project] %></td>
    <td><%= link_to 'Edit', edit_admin_project_path(project) %></td>
    <td><%= link_to 'Destroy', [:admin, project], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_admin_project_path %>

app/views/admin/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Imagen:</b>
  <%= image_tag @project.photo.url(:medium) %>
</p>

<p>
  <b>Desc corta:</b>
  <%= @project.desc_corta %>
</p>

<p>
  <b>Url:</b>
  <%= @project.url %>
</p>
<p>
  <b>year:</b>
  <%= @project.year %>
</p>
<b>labels:</b>
<% @project.skills.each do |s| %>
  <p>
    <%= s.name %>
  </p>
<% end %>

<%= link_to 'Edit', edit_admin_project_path(@project) %> |
<%= link_to 'Back', admin_projects_path %>