config/routes.rb
Portafolio::Application.routes.draw do

  get "welocme/index"
  get 'contact' => 'contact#new', as: 'contact'
  post 'contact' => 'contact#create', as: 'contact'

  match '/admin', to: 'admin/sessions#new'
  match '/admin/logout', to: 'admin/sessions#destroy', via: :delete

     namespace :admin do
        resources :sessions, only: [:new, :create]
        resources :projects
        resources :labels
        resources :users
        resources :skills
     end

   root :to => 'welcome#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  descriptin :text
#  ocupacion  :string(255)
#  image      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  mail       :string(255)
#  github     :string(255)
#  linkedin   :string(255)
#  celular    :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :descriptin, :ocupacion, :image, :skill_ids, :mail, :github, :linkedin, :celular
  has_many :skills
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_filter :auth
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to [:admin, @user], :notice => "Successfully created user."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    params[:user][:skill_ids] ||= []
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to [:admin, @user], :notice  => "Successfully updated user."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, :notice => "Successfully destroyed user."
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :descriptin %><br />
    <%= f.text_area :descriptin %>
  </p>
  <p>
    <%= f.label :ocupacion %><br />
    <%= f.text_field :ocupacion %>
  </p>
  <p>
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  <p>
  <p>
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  <p>
  <p>
    <%= f.label :github %><br />
    <%= f.text_field :github %>
  <p>
  <p>
    <%= f.label :linkedin %><br />
    <%= f.text_field :linkedin %>
  <p>
  <p>
    <%= f.label :celular %><br />
    <%= f.text_field :celular %>
  <p>
    <% Skill.all.each do |s| %>
      <%= check_box_tag 'user[skill_ids][]', s.id, @user.skills.include?( s ) %>
      <%= s.name %>
    <% end %>
  </p>
  <p><%= f.submit %></p>

<% end %>

app/views/admin/users/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", [:admin, @user] %> |
  <%= link_to "View All", admin_users_path %>
</p>

app/views/admin/users/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Descriptin</th>
    <th>Ocupacion</th>
    <th>Image</th>
    <th>E-mail</th>
    <th>Github</th>
    <th>Linkedin</th>
    <th>Celular</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.descriptin %></td>
      <td><%= user.ocupacion %></td>
      <td><%= user.image %></td>
      <td><%= user.mail %></td>
      <td><%= user.github %></td>
      <td><%= user.linkedin %></td>
      <td><%= user.celular %></td>
      <td><%= link_to "Show", [:admin, user] %></td>
      <td><%= link_to "Edit", edit_admin_user_path(user) %></td>
      <td><%= link_to "Destroy", [:admin, user], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Admin/User", new_admin_user_path %></p>

app/views/admin/users/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", admin_users_path %></p>

app/views/admin/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Descriptin:</strong>
  <%= @user.descriptin %>
</p>
<p>
  <strong>Ocupacion:</strong>
  <%= @user.ocupacion %>
</p>
<p>
  <strong>Image:</strong>
  <%= @user.image %>
</p>
<p>
  <strong>E-mail:</strong>
  <%= @user.mail %>
</p>
<p>
<p>
  <strong>Github:</strong>
  <%= @user.github %>
</p>
<p>
  <strong>Linkedin:</strong>
  <%= @user.linkedin %>
</p>
<p>
  <strong>Celular:</strong>
  <%= @user.celular %>
</p>
  <strong>Skills:</strong>
  <% @user.skills.each do |s| %>
    <%= s.name %>
    <%= s.percent %>
  <% end%>
</p>

<p>
  <%= link_to "Edit", edit_admin_user_path(@user) %> |
  <%= link_to "Destroy", [:admin, @user], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_users_path %>
</p>